# Generated by Django 5.2.11 on 2026-02-27 07:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(help_text='Client / Establishment Name', max_length=255)),
                ('request_date', models.DateField(default=django.utils.timezone.now)),
                ('contact_number', models.CharField(max_length=20)),
                ('barangay', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('service_type', models.CharField(choices=[('RESIDENTIAL_DESLUDGING', 'Residential Septage Desludging'), ('COMMERCIAL_DESLUDGING', 'Commercial Septage Desludging'), ('GRASS_CUTTING', 'Grass Cutting')], max_length=30)),
                ('connected_to_bawad', models.BooleanField(default=False)),
                ('bawad_proof', models.FileField(blank=True, null=True, upload_to='bawad_proofs/')),
                ('public_private', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PRIVATE', max_length=10)),
                ('client_signature', models.FileField(blank=True, null=True, upload_to='client_signatures/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('INSPECTION_SCHEDULED', 'Inspection Scheduled'), ('INSPECTED', 'Inspected'), ('COMPUTATION_SENT', 'Computation Sent'), ('AWAITING_PAYMENT', 'Awaiting Payment'), ('PAID', 'Paid'), ('DESLUDGING_SCHEDULED', 'Desludging Scheduled'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('scheduled_desludging_date', models.DateField(blank=True, null=True)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_notes', models.CharField(blank=True, max_length=255)),
                ('treasurer_receipt', models.FileField(blank=True, null=True, upload_to='treasurer_receipts/')),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cubic_meters', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('assigned_inspector', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['ADMIN', 'STAFF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_assigned', to=settings.AUTH_USER_MODEL)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=500)),
                ('notification_type', models.CharField(choices=[('REQUEST_SUBMITTED', 'Request Submitted'), ('INSPECTOR_ASSIGNED', 'Inspector Assigned'), ('COMPUTATION_READY', 'Computation Ready'), ('PAYMENT_UPLOADED', 'Payment Uploaded'), ('DESLUDGING_SCHEDULED', 'Desludging Scheduled'), ('STATUS_CHANGE', 'Status Change')], default='STATUS_CHANGE', max_length=30)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='services.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InspectionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField()),
                ('inspected_by', models.CharField(max_length=255)),
                ('inspector_signature', models.FileField(blank=True, null=True, upload_to='inspector_signatures/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_detail', to='services.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='CompletionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_completed', models.DateField()),
                ('time_required', models.CharField(help_text='e.g. 2 hours 30 mins', max_length=100)),
                ('witnessed_by_name', models.CharField(blank=True, max_length=255)),
                ('witnessed_by_signature', models.FileField(blank=True, null=True, upload_to='witness_signatures/')),
                ('declogger_no', models.CharField(blank=True, max_length=50)),
                ('fuel_consumption', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fuel_unit', models.CharField(default='liters', max_length=20)),
                ('driver_name', models.CharField(max_length=255)),
                ('driver_signature', models.FileField(blank=True, null=True, upload_to='driver_signatures/')),
                ('helper1_name', models.CharField(blank=True, max_length=255)),
                ('helper1_signature', models.FileField(blank=True, null=True, upload_to='helper_signatures/')),
                ('helper2_name', models.CharField(blank=True, max_length=255)),
                ('helper2_signature', models.FileField(blank=True, null=True, upload_to='helper_signatures/')),
                ('helper3_name', models.CharField(blank=True, max_length=255)),
                ('helper3_signature', models.FileField(blank=True, null=True, upload_to='helper_signatures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion_info', to='services.servicerequest')),
            ],
        ),
    ]
