# Generated by Django 5.2.9 on 2026-03-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='location_mode',
            field=models.CharField(choices=[('PIN', 'Pin on Map'), ('TEXT', 'Type Address')], default='PIN', max_length=10),
        ),
    ]
