# Generated by Django 5.2.9 on 2026-03-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_location_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='location_photo_1',
            field=models.ImageField(blank=True, null=True, upload_to='location_photos/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='location_photo_2',
            field=models.ImageField(blank=True, null=True, upload_to='location_photos/'),
        ),
    ]
