# Generated by Django 5.2.11 on 2026-03-12 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_grasscutting_fields_and_changelog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Account that submitted the request when requesting for another person.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('INSPECTION_SCHEDULED', 'Inspection Scheduled'), ('INSPECTED', 'Inspected'), ('COMPUTATION_SENT', 'Computation Sent'), ('AWAITING_PAYMENT', 'Awaiting Payment Verification'), ('PAID', 'Paid'), ('DESLUDGING_SCHEDULED', 'Desludging Scheduled'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=25),
        ),
    ]
