# Generated by Django 5.2.11 on 2026-03-13 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicerequest_requested_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='inspection_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='inspection_fee_receipt',
            field=models.FileField(blank=True, null=True, upload_to='inspection_fee_receipts/'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('INSPECTION_FEE_DUE', 'Inspection Fee Due'), ('INSPECTION_FEE_AWAITING_VERIFICATION', 'Inspection Fee Awaiting Verification'), ('UNDER_REVIEW', 'Under Review'), ('INSPECTION_SCHEDULED', 'Inspection Scheduled'), ('INSPECTED', 'Inspected'), ('COMPUTATION_SENT', 'Computation Sent'), ('AWAITING_PAYMENT', 'Awaiting Payment Verification'), ('PAID', 'Paid'), ('DESLUDGING_SCHEDULED', 'Desludging Scheduled'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=40),
        ),
    ]
