# Generated by Django 5.2.11 on 2026-04-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_servicerequest_inspection_fee_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('INSPECTION_FEE_DUE', 'Inspection Fee Due'), ('INSPECTION_FEE_AWAITING_VERIFICATION', 'Inspection Fee Awaiting Verification'), ('EXPIRED', 'Expired'), ('UNDER_REVIEW', 'Under Review'), ('INSPECTION_SCHEDULED', 'Inspection Scheduled'), ('INSPECTED', 'Inspected'), ('COMPUTATION_SENT', 'Computation Sent'), ('AWAITING_PAYMENT', 'Awaiting Payment Verification'), ('PAID', 'Paid'), ('DESLUDGING_SCHEDULED', 'Desludging Scheduled'), ('COMPLETED', 'Completed'), ('GRASS_PENDING_PAYMENT', 'Pending Payment'), ('GRASS_PAYMENT_AWAITING_VERIFICATION', 'Payment Receipt Awaiting Verification'), ('CANCELLED', 'Cancelled')], default='SUBMITTED', max_length=40),
        ),
    ]
