# Generated by Django 5.2.11 on 2026-04-19 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_servicerequest_waived_crew_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=50, unique=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Service equipment',
                'ordering': ['unit_number'],
            },
        ),
        migrations.AddField(
            model_name='completioninfo',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completions', to='services.serviceequipment'),
        ),
    ]
