# Generated by Django 5.2.11 on 2026-02-27 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('RESIDENTIAL', 'Residential'), ('COMMERCIAL', 'Commercial')], max_length=20, unique=True)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Base rate per cubic meter or unit', max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Charge Categories',
            },
        ),
        migrations.CreateModel(
            name='ConfigurableRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, unique=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Configurable Rate',
                'verbose_name_plural': 'Configurable Rates',
            },
        ),
        migrations.CreateModel(
            name='DecloggingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_signature', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('applicant_sign_date', models.DateField(blank=True, null=True)),
                ('cenro_signature', models.FileField(blank=True, null=True, upload_to='signatures/')),
                ('cenro_sign_date', models.DateField(blank=True, null=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_signed', models.BooleanField(default=False)),
                ('cenro_representative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declogging_apps_signed', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declogging_app', to='services.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='MembershipRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_free', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership_record', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceComputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_outside_bayawan', models.BooleanField(default=False)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('cubic_meters', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('trips', models.PositiveIntegerField(default=1)),
                ('personnel_count', models.PositiveIntegerField(default=4)),
                ('fixed_trucking', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('desludging_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('distance_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wear_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('meals_transport_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inspection_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FREE', 'Free (BAWAD)')], default='PENDING', max_length=20)),
                ('receipt_generated', models.BooleanField(default=False)),
                ('receipt_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.chargecategory')),
                ('prepared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='computations_prepared', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='computation', to='services.servicerequest')),
            ],
        ),
    ]
