# Generated by Django 5.2.11 on 2026-03-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecomputation',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecomputation',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicecomputation',
            name='prepared_by_signature',
            field=models.FileField(blank=True, null=True, upload_to='computation_signatures/'),
        ),
    ]
