# Generated by Django 5.2.11 on 2026-03-10 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_servicecomputation_finalized_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecomputation',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_VERIFICATION', 'Awaiting Verification'), ('PAID', 'Paid'), ('FREE', 'Free (BAWAD)')], default='PENDING', max_length=25),
        ),
    ]
