# Generated by Django 5.2.11 on 2026-03-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_payment_status_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecomputation',
            name='distance_travel_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
