# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0007_servicecomputation_ready_to_finalize"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecomputation",
            name="letter_signatory_signature",
            field=models.FileField(
                blank=True,
                help_text="Scanned signature for the letter signatory (e.g. City ENRO), shown above the closing block.",
                null=True,
                upload_to="computation_signatures/",
            ),
        ),
    ]
