# Generated by Django 5.2.11 on 2026-02-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_municipality'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
