# Generated by Django 5.2.11 on 2026-02-27 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_consumerprofile_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='consumerprofile',
            name='location_type',
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='province',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='street_address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
