# Generated by Django 5.2.11 on 2026-02-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_consumerprofile_birthdate_consumerprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
