# Generated by Django 5.2.11 on 2026-03-10 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_consumerprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='If true, user must change password on next login (used for staff temporary passwords).'),
        ),
    ]
