# Generated by Django 5.2.9 on 2026-04-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_must_change_password_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
