# Generated by Django 5.2.11 on 2026-04-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_passwordresettoken_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerprofile',
            name='last_cycle_request_date',
            field=models.DateField(blank=True, help_text='Date when the account last had a desludging request counted for the current cycle (manual/pre-system).', null=True),
        ),
    ]
