# Generated by Django 5.2.11 on 2026-04-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_consumerprofile_prior_desludging_m3_4y'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('NON_BINARY', 'Non-binary')], default='MALE', max_length=20),
        ),
    ]
